### ISSUE TITLE
README.md jenkins command

### ISSUE THREAD

**Issue by wblankenship** [iojs/build-containers#15]
_README.md_ states:

For reference, the Jenkins build server for io.js runs the following command:

    docker run -a stdin -a stdout -a stdin -t --rm -v ${PWD}:/opt/node/ node-forward-ci:node-${DISTRO}

`-a stdin -a stdout -a stdin`

Is this supposed to be `-a stdin -a stdout -a stderr`?

**Comment by wblankenship** [comment]
Also `/opt/node` should be `/opt/iojs` correct?

**Comment by rvagg** [comment]
yes, that's wrong on many counts actually! This is the current:

```
docker run -a stdout -a stderr -t --rm -v `pwd`:/opt/iojs/ iojs/build:iojs-${DISTRO}
```

I had to remove the `-a stdin` because the latest Docker doesn't seem to like it on headless builds.

would you mind fixing it @wblankenship?
