### ISSUE TITLE
Child process + pipe tests now failing in Docker

### ISSUE THREAD

**Issue by rvagg** [iojs/build-containers#9]
I've just noticed this, having installed Docker 1.3.2 and running the containers locally, I get `EACCES` type failures with about 5 of the tests. They all seem to be about child processes and pipes and are related to Docker's new security model. If you run with `--privileged` then it's fine but that's not desirable for us. It's not a capabilities-related thing because `--cap-add=all` doesn't make a difference.

For test/simple/test-cluster-http-pipe.js at least (the one I've been mainly focusing on), I've narrowed it down to a `read()` on the pipe file descriptor on the child in libuv, the `connect()` is fine, it's only when you start reading that you get the `EACCES`. My instinct here is to blame Docker, but it's possible that libuv, or even Node, are doing something wrong. The error is as if we're trying to read from protected /dev/ nodes but I'm pretty sure we're note going anywhere near them. No matter where the pipe is put (can be changed with the `NODE_COMMON_PIPE` env var) it still happens, I've tried /opt/iojs/test.pipe, /tmp/test.pipe, /home/iojs/test.pipe and others to no avail.

If anyone else has a clue or time to chase this down it's be greatly appreciated because this is a big blocker now to getting tests happening on pull requests. I don't even know where to escalate this bug to at the moment or even if it's just isolated to my machine!

**Comment by bnoordhuis** [comment]
Haven't forgotten about this.  Assigning to myself.

**Comment by bnoordhuis** [comment]
I think this issue has gone stale.  Closing, holler if it's still relevant.
